# Generated by Django 2.1.4 on 2018-12-29 04:43

from django.db import migrations
from django.contrib.auth.models import User

def dbinit(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User.objects.create_user(username='admin', password='admin', is_active=True,is_superuser=True,is_staff=True)

    # UserModel.objects.create_user(username='admin', password='adminadmin', is_active=True)
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(dbinit)
    ]
