# Generated by Django 2.0.7 on 2019-01-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('desc', models.TextField(verbose_name='文章描述')),
                ('type', models.CharField(choices=[(0, '文本'), (1, 'markdown'), (2, 'UEditor')], max_length=2, verbose_name='编辑类型')),
                ('content', models.TextField(verbose_name='文章正文')),
            ],
        ),
    ]
