# Generated by Django 2.1.4 on 2019-03-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
