# Generated by Django 2.1 on 2018-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='/frontend/storage/images/common/cate_banner.jpg', upload_to='frontend/storage/uploads/', verbose_name='图片'),
        ),
    ]
