# Generated by Django 2.0.7 on 2018-07-14 08:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0003_auto_20180314_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, unique=True, verbose_name='名称')),
                ('explain', models.CharField(default='', max_length=30, verbose_name='说明')),
                ('intro', models.TextField(default='', verbose_name='简介')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='文档内容')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('content', models.TextField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pub_date', models.DateTimeField(blank=True, default=None, help_text='选择文章实际的发布时间，默认为文章创建时间。', null=True, verbose_name='发布时间')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('page_view', models.IntegerField(default=0, verbose_name='浏览量')),
                ('status', models.IntegerField(choices=[(1, '已发布'), (0, '草稿')], default=1, verbose_name='状态')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete='', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ManyToManyField(default=None, to='share.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '会员', 'verbose_name_plural': '会员'},
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='./frontend/static/images/indexView/house.png', upload_to='uploads/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男'), (-1, '暂时保密')], default=-1, verbose_name='性别'),
        ),
    ]
